# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "libxev-0.0.0-86vtcx8dEwDfl6p4tGVxCygft8oOsggfba9JO-k28J2x";
    path = fetchzip {
      url = "https://github.com/mitchellh/libxev/archive/9f785d202ddccf7a625e799250579253977978b6.tar.gz";
      hash = "sha256-9dD7TIW5n3rHIPCdpxiVEdVqXs/cslR+VP8XN9H9Efc=";
    };
  }
]
