# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "libxev-0.0.0-86vtc4b1EgCl0Kvo2Ixmjfl5PgAaJmvCXRIn_n89nCaR";
    path = fetchzip {
      url = "https://github.com/mitchellh/libxev/archive/5647630d7bff969414a0edc24c03c30aff34b101.tar.gz";
      hash = "sha256-nlJzFS/4BdKUmBwacdvEmFRn+E8YWnD6R/c2OcStd7w=";
    };
  }
]
